repos:
- repo: local
  hooks:
    - id: pytest-cov
      name: pytest
      entry: uv run python -m pytest --cov --cov-report= --cov-fail-under=80
      language: system
      pass_filenames: false
      always_run: true
