repos:
-   repo: local
    hooks:
    -   id: pytest-local
        name: Run local python tests
        entry: uv run
        language: system
        types: [python]
        stages: [pre-commit]
        verbose: true
