repos:
-   repo: local
    hooks:
    -   id: pytest-local
        name: Run local python tests
        entry: uv run pytest tests/test_unit_s3.py tests/test_unit_ec2.py
        language: system
        types: [python]
        stages: [pre-commit]
        verbose: true
