[project]
name = "aws-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.13",
]

[tool.uv]
dev-dependencies = [
    "pre-commit>=4.3.0",
    "pytest>=8.0.0",
    "pytest-cov>=4.0.0",
]
