#!/usr/bin/env sh
set -e

WORKDIR="$(pwd)"
HOME_DIR="${HOME:-/root}"

# Set docker flags. Only add -it if we're in an interactive terminal
DOCKER_FLAGS="--rm"
if [ -t 0 ]; then
  DOCKER_FLAGS="$DOCKER_FLAGS -it"
fi

exec docker run $DOCKER_FLAGS \
  -v "$WORKDIR:/work" -w /work \
  -v "$HOME_DIR:/root" \
  --entrypoint awsctl \
  awsctl:latest "$@"
